//POST LOGIN DE USUARIO TEST
POST http://localhost:3001/clientes/login HTTP/1.1
content-type: application/json

{
    "email":"6@gmail.com",
    "password":"prueba123"
}
###
//POST REGISTRO DE USUARIO TEST
POST http://localhost:3001/clientes/register HTTP/1.1
content-type:application/json

{
  "name":"prueba2",
  "email":"6@gmail.com",
  "password":"prueba123",
  "cellphone":"6645861400"
}
###
//GET MESAS
GET http://localhost:3001/mesas/all HTTP/1.1